name: 'Max Hancock & Co.'
favicon: null
layout_spectrum: 0.07693
typography_spectrum: 0.32977
title: 'A journal of illustrations, art and ideas from Max Hancock & Company.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d9ae21'
    - '#414141'
    - '#8f8f8f'
  brandStrength: 0.5528712249360979
  lightness: 0.6161263121757656
  saturation: 0.5036663564387709
  rhythmicContrast: 0.5895087255630642
purpose: []
