name: Max Hancock & Co.
favicon: null
layout_spectrum: 0.2375970899593085
typography_spectrum: 0.9465180290862918
title: 'A journal of illustrations, art and ideas from Max Hancock & Company.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.7838962567038834
  lightness: 0.7929651101585478
  saturation: 0.16710861981846392
  rhythmicContrast: 0.013117911061272025
purpose: []
